nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Raquel Manzano-Garcia
  description: Pipeline for RNA and DNA integrated analysis for somatic mutation detection
  force: false
  is_nfcore: true
  name: rnadnavar
  org: nf-core
  outdir: .
  version: 1.0dev
lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
modules_config: False
files_unchanged:
  - LICENSE
  - assets/nf-core-rnadnavar_logo_light.png
  - docs/images/nf-core-rnadnavar_logo_dark.png
  - docs/images/nf-core-rnadnavar_logo_light.png
schema_params: False
template_strings: False
multiqc_config: False
