# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "command_validation"
description: Validate command syntax and parameters before execution
keywords:
  - validation
  - command
  - syntax
  - parameters
  - error-prevention
components:
  - command_validation
input:
  - process_name:
      type: string
      description: Name of the process for validation context
  - command_parts:
      type: map
      description: |
        Command components to validate including:
        - executable: Command executable (required)
        - args: Command arguments as List or String (required)
        - input_files: Input files to validate (optional)
        - output_files: Output files to validate (optional)
        - resources: Resource requirements to validate (optional)
output:
  - validated_command:
      type: map
      description: |
        Validated command parts with additional metadata:
        - All original fields
        - validated: true
        - full_command: Constructed full command string
        - validation_timestamp: When validation occurred
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vcf-realignment-optimization"
maintainers:
  - "@vcf-realignment-optimization"