name: "error_safe_process"
description: Wrapper for safe process execution with comprehensive error handling and StackOverflowError detection
keywords:
  - error-handling
  - stackoverflow
  - safety
  - diagnostics
  - monitoring
  - debugging
components:
  - error_safe_process
input:
  - process_name:
      type: string
      description: Name of the process for error reporting and logging
  - input_channel:
      type: channel
      description: |
        Input channel to be processed safely
        Can contain any channel structure
  - process_closure:
      type: closure
      description: |
        The actual process logic to execute (optional parameter for future extension)
        Currently not used but reserved for advanced error handling scenarios
output:
  - output:
      type: channel
      description: |
        Safely processed channel with comprehensive error handling applied
        Structure preserved from input
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vcf-realignment-optimization"
maintainers:
  - "@vcf-realignment-optimization"