name: "process_monitoring"
description: Comprehensive logging and monitoring for channel operations with resource usage tracking
keywords:
  - monitoring
  - logging
  - channels
  - debugging
  - memory
  - validation
components:
  - process_monitoring
input:
  - process_name:
      type: string
      description: Name of the process being monitored for logging purposes
  - input_channel:
      type: channel
      description: |
        Any Nextflow channel to be monitored and logged
        Can contain any channel structure (tuples, files, etc.)
output:
  - output:
      type: channel
      description: |
        The same channel as input but with comprehensive monitoring applied
        Structure preserved from input
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vcf-realignment-optimization"
maintainers:
  - "@vcf-realignment-optimization"